### PR TITLE
resolve a compilation error of VTK-m with CUDA 12.6

### LINKED ISSUE #1506: vtk-m-v2.2.0 does not compile with CUDA 12.6
Testing ascent develop branch on a Grace Hopper cluster

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Fri_Jun_14_16:44:37_PDT_2024
Cuda compilation tools, release 12.6, V12.6.20
Build cuda_12.6.r12.6/compiler.34431801_0

/capstor/scratch/cscs/jfavre/Ascent-cuda/source/vtk-m-v2.2.0/vtkm/exec/cuda/internal/WrappedOperators.h(198): error: namespace "thrust::THRUST_200500_800_NS::detail" has no member class "is_arithmetic"
    : public thrust::detail::is_arithmetic<T>

### PR DESCRIPTION
**Pull request by jfavre**
we resolve https://github.com/Alpine-DAV/ascent/issues/1506 by applying the same patch used in vtkm-2.3 source code.

### CODE REVIEW

**Comment by cyrush** [comment]
thanks @jfavre  -- we will be moving to VTK-m 2.3.0 soon!
