### ISSUE TITLE
compilation error with CUDA 12.2.91

### ISSUE THREAD

**Issue by jfavre** [Alpine-DAV/ascent#1178]
[ 47%] Building CUDA object libs/vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/vtkmPointTransform.cpp.o
cd /local/apps/Ascent/build/ascent-develop/libs/vtkh/vtkm_filters && /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/g++  --options-file CMakeFiles/vtkm_compiled_filters.dir/includes_CUDA.rsp -Xnvlink=--suppress-stack-size-warning --expt-extended-lambda --expt-relaxed-constexpr  -Xptxas --disable-optimizer-constants -O3 -DNDEBUG -std=c++14 --generate-code=arch=compute_86,code=[compute_86,sm_86] -Xcompiler=-fPIC --expt-relaxed-constexpr -Xcompiler=-ffunction-sections -MD -MT libs/vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/vtkmPointTransform.cpp.o -MF CMakeFiles/vtkm_compiled_filters.dir/vtkmPointTransform.cpp.o.d -x cu -rdc=true -c /local/apps/Ascent/ascent/src/libs/vtkh/vtkm_filters/vtkmPointTransform.cpp -o CMakeFiles/vtkm_compiled_filters.dir/vtkmPointTransform.cpp.o

/local/apps/Ascent/ascent/src/libs/vtkh/vtkm_filters/vtkmPointTransform.cpp(15): error: no suitable user-defined conversion from "vtkm::Matrix<double, 4, 4>" to "const vtkm::Matrix<vtkm::FloatDefault, 4, 4>" exists
    trans.SetTransform(transform);
                       ^

P.S. The same code compiles fine with cuda 11.6
