### ISSUE TITLE
ENABLE_MPI causes undefined reference to `conduit::relay::mpi::send_using_schema(conduit::Node const&, int, int, int)'

### ISSUE THREAD

**Issue by yurivict** [Alpine-DAV/ascent#813]
```
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::send_using_schema(conduit::Node const&, int, int, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::max_all_reduce(conduit::Node const&, conduit::Node&, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::min_all_reduce(conduit::Node const&, conduit::Node&, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::recv_using_schema(conduit::Node&, int, int, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::broadcast_using_schema(conduit::Node&, int, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::size(int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::recv(conduit::Node&, int, int, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::send(conduit::Node const&, int, int, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::rank(int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::sum_all_reduce(conduit::Node const&, conduit::Node&, int)'
/usr/local/bin/ld: ../../lib/libascent_mpi.so: undefined reference to `conduit::relay::mpi::all_gather_using_schema(conduit::Node&, conduit::Node&, int)'
```

Version: 0.7.1
conduit-0.7.2
clang-11
FreeBSD 13

**Comment by cyrush** [comment]
@yurivict thanks for the report, can you share how conduit was configured? It seems like conduit was not built with MPI support.
If this is the case I would have expected it ascent to fail at compile time, not link time - as in #812.

MPI in Ascent does require Conduit's MPI support.  I could strengthen some of the cmake configure checks if that is not clear.

**Comment by yurivict** [comment]
```conduit``` was configured with ```-DENABLE_MPI=ON```.

**Comment by cyrush** [comment]
Thanks, is there is some why I can try to replicate easily?

**Comment by yurivict** [comment]
I found this while creating the FreeBSD port.

So if you could install FreeBSD into a VM, and try to compile the port science/ascent with the MPI line removed - you should be able to reproduce the problem.
