### PR TITLE
ContourTree Filter Enhancements

### PR DESCRIPTION
**Pull request by abessiari**
- Made sure it compiles when VTKH_ENABLE_FILTER_CONTOUR_TREE is ON. 
- No longer computing block indices externally. This is done in the filter now. 
- Calling ShiftLogicalOriginToZero and ComputeGlobalPointSize before filter.execute()
-  Initializing Kokkos in unit test when VTKM_ENABLE_KOKKOS is ON

### CODE REVIEW

**Comment by abessiari** [comment]
@nicolemarsaglia @cyrush 
CC: @ghweber 

Hi Nicole and Cyrus,

We would like to have this PR merged. The changes relate to contour tree augmented. 
I have tested on Crusher using ascent contour tree unit test and the warpx binary ranks 1 to 8.

Please let me know what else I need to do on my end. Thanks.
aes

**Comment by cyrush** [comment]
@abessiari thanks for the pulse and the report that you have it working on crusher.

I want to double check we are building VTK-m in our CI to support this.

With VTK-m 1.9 - I believe if we have `vtkm_filter_scalar_topology` we are OK on the VTK-m front. I checked a container install this lib is there for VTK-m.

Assuming this matches what you expect, then lets change the default:

`VTKH_ENABLE_FILTER_CONTOUR_TREE` to `ON`

https://github.com/Alpine-DAV/ascent/blob/38906d1efeadb2b389d733b6e0d38e0a4cf8c055/src/CMakeLists.txt#L49

So we will always be building it.

**Comment by cyrush** [comment]
@abessiari 
```
/__w/1/s/src/tests/vtkh/t_vtk-h_contour_tree.cpp:19:10: fatal error: vtkm/worklet/contourtree_augmented/Types.h: No such file or directory
   19 | #include <vtkm/worklet/contourtree_augmented/Types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The current CI is testing against VTK-m 1.9, i don't see `worklet/contourtree_augmented`, only `filters/scalar_topology`

Does this work need VTK-m 2.0? (We are working on updating to VTK-m 2.0 in other branches)

**Comment by abessiari** [comment]
@cyrush 

I fixed the include.  Yes we are building against VTK-m 1.9. I was enabling VTKm_ENABLE_MPI which
was builds the parallel version. As of now I cannot access my directory under /gpfs/alpine/proj-shared/csc340
so I could not test the non parallel build. ... But I will when I get a chance. Thanks

**Comment by cyrush** [comment]
One issue still remains:

```
 D:\a\ascent\ascent\src\tests\vtkh\t_vtk-h_contour_tree.cpp(51,1): error C2026: string too big, trailing characters truncated [D:\a\ascent\ascent\build\tests\vtkh\t_vtk-h_contour_tree.vcxproj]
```

Windows wont accept long strings.

Can we save this data set as `fuel.txt` under: 

`src/tests/_test_data`

There are helpers we can use to locate that file and use it in the tests.

**Comment by abessiari** [comment]
@cyrush 

I am now using the fuel.txt under src/tests/_test_data.
Not sure why all the checks are failing ....
Thanks

**Comment by nicolemarsaglia** [comment]
@abessiari we just switched over to building against VTKm 2.0, and it looks like the contour tree headers files are in a new location.

**Comment by abessiari** [comment]
> @abessiari we just switched over to building against VTKm 2.0, and it looks like the contour tree headers files are in a new location.
Thanks.

**Comment by abessiari** [comment]
Contour tree tests are failing when using vtkm 2.0.0. Closing this PR for now.

**Comment by abessiari** [comment]
@cyrush @nicolemarsaglia 

The contour tree tests now compile and work both for serial and MPI on crusher against vtkm 2.0.0

**Review by cyrush — APPROVED** [review]
Thanks @abessiari !
