### ISSUE TITLE
build of dray fails with CUDA 12

### ISSUE THREAD

**Issue by jfavre** [Alpine-DAV/ascent#1156]
I have verified (On a Cray node) that the build of the current develop version (including https://github.com/Alpine-DAV/ascent/pull/1147) works well with CUDA 11.6 but fails to build on my workstation with CUDA 12. All dependencies compile successfully, but Ascent itself does not compile with the first error being:

[  5%] Building CUDA object libs/dray/CMakeFiles/dray.dir/filters/clipfield.cpp.o
cd /local/apps/tmp/build/ascent-develop/libs/dray && /usr/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/bin/g++ -DASCENT_
EXPORTS_FLAG -DCAMP_HAVE_CUDA -DH5_BUILT_AS_DYNAMIC_LIB -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_LARGEFILE_SO
URCE -D_POSIX_C_SOURCE=200809L -Ddray_EXPORTS --options-file CMakeFiles/dray.dir/includes_CUDA.rsp -Xnvlink=--suppress-stack-size-
warning --expt-extended-lambda --expt-relaxed-constexpr  -Xptxas --disable-optimizer-constants -O3 -DNDEBUG -std=c++14 --generate-
code=arch=compute_80,code=[compute_80,sm_80] -Xcompiler=-fPIC -I/local/apps/tmp/install/conduit-v0.8.7/include/conduit -MD -MT lib
s/dray/CMakeFiles/dray.dir/filters/clipfield.cpp.o -MF CMakeFiles/dray.dir/filters/clipfield.cpp.o.d -x cu -rdc=true -c /local/app
s/tmp/ascent/src/libs/dray/filters/clipfield.cpp -o CMakeFiles/dray.dir/filters/clipfield.cpp.o
In file included from tmpxft_0001217c_00000000-6_clipfield.cudafe1.stub.c:1:
/tmp/tmpxft_0001217c_00000000-6_clipfield.cudafe1.stub.c:51:335: error: type/value mismatch at argument 3 in template parameter li
st for ‘template<bool IsMutable, bool HasFuncPtrConv, bool NeverThrows, class Tag, class OpFunc, class ... CapturedVarTypePack> st
ruct __nv_hdl_wrapper_t’
   51 | typedef camp::decay< ::__nv_hdl_wrapper_t<false,false,__nv_dl_tag<void ( :: dray::detail::ClipFieldLinear::*)(const  ::dra
y::Array<unsigned int>  &,  ::dray::Array<unsigned int>  &,  ::dray::Array<unsigned int>  &),(& :: dray::detail::ClipFieldLinear::
unique), 1> ,void (unsigned int),unsigned int *,const unsigned int *,unsigned int *>>  _ZN4camp5decayIZN4dray6detail15ClipFieldLin
ear6uniqueERKNS1_5ArrayIjEERS5_S8_EUljE_EE;

**Comment by nicolemarsaglia** [comment]
Thanks for the update and reporting this crash! Looking at our CI, we only support up to 11.8. 

Sounds like the dependencies aren't limited to the newer version and we have some updating to do.

**Comment by cyrush** [comment]
@jfavre  Can you tell me which version of cuda 12?

I was able to build static with our spack-based builds using cuda 12.1.1 in an ubuntu container. 

I will look into shared next to see if I can trigger the issue.

**Comment by cyrush** [comment]
Update on my testing: I was able to successfully build on ubuntu 20.04 w/ 12.1.1 with shared libs as well.

**Comment by jfavre** [comment]
I have the following:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

**Comment by jfavre** [comment]
there was a mix of nvcc libs on my desktop which might have caused the problem above. I can no longer reproduce. I will close it.
