### ISSUE TITLE
2021 07 or 08 spack fork update

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#780]
todo:

- [x] new fides spack pkg (https://github.com/spack/spack/pull/25128)
- [x] test in ci for ubuntu 18, ubuntu 18 + cuda 10, ubuntu 20.10, ubuntu 21.4
- [x] test develop cuda and non cuda build on summit 
- [x] update uberenv
- [x] update spack configs (new spack yaml format)
- [x] dray updates to use new raja
- [x] update ascent proper package to add fides and adios2 deps

**Comment by cyrush** [comment]
current spack w/o system libs fails to build on ubuntu 21.04:

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

2 errors found in build log:
     227      CCLD     gdbm_dump
     228      CCLD     gdbm_load
     229    /usr/bin/ld: /usr/bin/ld: ./libgdbmapp.a(parseopt.o):./libgdbmapp.a(parseopt.o)/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egy
            swxit56qpztsa427dailcvbhk7pvk/spack-src/src/parseopt.c::/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvb
            hk7pvk/spack-src/src/parseopt.c:259259: multiple definition of `: multiple definition of `parseopt_program_argsparseopt_program_args''; ; gdbm_dump.o:/asc
            ent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvbhk7pvk/spack-src/src/gdbm_dump.c:23: first defined here
     230    /usr/bin/ld: ./libgdbmapp.a(parseopt.o):/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvbhk7pvk/spack-src
            /src/parseopt.c:258: multiple definition of `parseopt_program_doc'; gdbm_dump.o:/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-eg
            yswxit56qpztsa427dailcvbhk7pvk/spack-src/src/gdbm_dump.c:22: first defined here
     231    gdbm_load.o:/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvbhk7pvk/spack-src/src/gdbm_load.c:33: first d
            efined here
     232    /usr/bin/ld: ./libgdbmapp.a(parseopt.o):/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvbhk7pvk/spack-src
            /src/parseopt.c:258: multiple definition of `parseopt_program_doc'; gdbm_load.o:/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-eg
            yswxit56qpztsa427dailcvbhk7pvk/spack-src/src/gdbm_load.c:32: first defined here
  >> 233    collect2: error: ld returned 1 exit status
  >> 234    collect2: error: ld returned 1 exit status
     235    make[3]: *** [Makefile:648: gdbm_dump] Error 1
     236    make[3]: *** Waiting for unfinished jobs....
     237    make[3]: *** [Makefile:652: gdbm_load] Error 1
     238    make[3]: Leaving directory '/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvbhk7pvk/spack-src/src'
     239    make[2]: *** [Makefile:499: all] Error 2
     240    make[2]: Leaving directory '/ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvbhk7pvk/spack-src/src'

See build log for details:
  /ascent/uberenv_libs/spack/var/spack/stage/root/spack-stage-gdbm-1.18.1-egyswxit56qpztsa427dailcvbhk7pvk/spack-build-out.txt
```

**Comment by cyrush** [comment]
in #790

updated to new spack, using pending updates for the latest coupled releases of raja,umpire and camp.

dray needs to be updated to use these b/c of API changes to raja (we expected this)

**Comment by cyrush** [comment]
we will handle occa later

**Comment by cyrush** [comment]
resolved in #790
