### ISSUE TITLE
vtk-m build fails with Kokkos 4.1.00

### ISSUE THREAD

**Issue by BenWibking** [Alpine-DAV/ascent#1172]
We need to track the latest Kokkos version for improved HIP performance on Frontier.

VTK-m 2.0 fails to build with Kokkos 4.1.00 due to its use of internal `Kokkos::Impl` APIs that are not guaranteed to be stable:
```
/lustre/orion/ast146/proj-shared/wibking/ascent/vtk-m-v2.0.0/vtkm/Atomic.h:334:46: error: no member named 'memory_order_relaxed' in namespace 'Kokkos::Impl'; did you mean 'std::memory_order_relaxed'?
      return Kokkos::Impl::atomic_load(addr, Kokkos::Impl::memory_order_relaxed);
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                             std::memory_order_relaxed
```

It would be good for the VTK-m team to be aware of it, but I can't immediately find if they have a public issue tracker, so posting here for now.

**Comment by cyrush** [comment]
@BenWibking thanks for the report, I passed this on to the VTK-m team. 

For future reference, here is their issue tracker as well:

https://gitlab.kitware.com/vtk/vtk-m/-/issues

**Comment by vicentebolea** [comment]
@cyrush @BenWibking we recently started testing with kokkos 4.1 in our CI. See here: https://gitlab.kitware.com/vtk/vtk-m/-/merge_requests/3098

**Comment by BenWibking** [comment]
This works with the development version of VTK-m, so I'll close.
