### ISSUE TITLE
upstream build errors on aurora

### ISSUE THREAD

**Issue by mlohry** [Alpine-DAV/ascent#1477]
I'm hitting a couple upstream build errors on aurora running the install scripts with oneapi compilers.

In vtk-m some bugs,

```
ascent/scripts/build_ascent/source/vtk-m-v2.1.0/vtkm/filter/scalar_topology/worklet/contourtree_distributed/HierarchicalContourTree.h:666:33: error: no member named 'whichRound' in 'HierarchicalContourTree<FieldType>'; did you mean 'WhichRound'?
  666 |   auto whichRoundPortal = this->whichRound.ReadPortal();
      |                                 ^~~~~~~~~~
      |                                 WhichRound
ascent/scripts/build_ascent/source/vtk-m-v2.1.0/vtkm/filter/scalar_topology/worklet/contourtree_distributed/HierarchicalContourTree.h:135:53: note: 'WhichRound' declared here
  135 |   vtkm::worklet::contourtree_augmented::IdArrayType WhichRound;
      |                                                     ^
ascent/scripts/build_ascent/source/vtk-m-v2.1.0/vtkm/filter/scalar_topology/worklet/contourtree_distributed/HierarchicalContourTree.h:711:55: error: no member named 'NRounds' in 'HierarchicalContourTree<FieldType>'; did you mean 'NumRounds'?
  711 |       if (whichRoundPortal.Get(superarcFrom) == this->NRounds)
      |                                                       ^~~~~~~
      |                                                       NumRounds
ascent/scripts/build_ascent/source/vtk-m-v2.1.0/vtkm/filter/scalar_topology/worklet/contourtree_distributed/HierarchicalContourTree.h:148:12: note: 'NumRounds' declared here

...

ascent/scripts/build_ascent/source/vtk-m-v2.1.0/vtkm/filter/contour/worklet/mir/MIRTables.h:11405:20: error: no member named 'CellFacePortal' in 'MIRDevicePortal<DeviceAdapter>'; did you mean 'CellEdgesPortal'?

```

which appear to have been fixed in recent commits. Fixing those, moves on to RAJA, hit with this error:

```
ascent/scripts/build_ascent/source/RAJA-v2024.02.1/include/RAJA/pattern/kernel/Tile.hpp:174:30: error: no member named 'block_id' in 'IterableTiler<Iterable>'
  174 |       return block_id != rhs.block_id;
      |                          ~~~ ^
ascent/scripts/build_ascent/source/RAJA-v2024.02.1/include/RAJA/pattern/kernel/Tile.hpp:180:29: error: no member named 'block_id' in 'IterableTiler<Iterable>'
  180 |       return block_id < rhs.block_id;
      |                         ~~~ ^
```

**Comment by cyrush** [comment]
@mlohry thanks for the report. We are working on updating to vtk-m 2.2 for our next release.

Here is the fix for the raja issue:

https://github.com/LLNL/RAJA/pull/1668

Which we can patch for now and resolve later with a new raja releas.e
